### ISSUE TITLE
<spike> Explore TypeORM

### ISSUE THREAD

**Issue by LogicUI** [LogicUI/Telegram-messages-stat-bot#11]
Currently, there are 2 ORMs being considered for the project 

TypeORM vs Mongoose
- Do a Basic tutorial and write in a description on how to setup typeORM
- Compare it to Mongoose
- use it with Express playground

**Comment by leelhn2345** [comment]
i've never used prisma, but i heard it's quite good

https://github.com/prisma/prisma
